name: Angelos
favicon: null
layout_spectrum: 0.91203
typography_spectrum: 0.5845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8a79d'
    - '#d8c9b8'
    - '#645c57'
    - '#2a2529'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
