name: Angelos
favicon: null
layout_spectrum: 0.6868628892116249
typography_spectrum: 0.0776806203648448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecebe9'
    - '#030303'
    - '#ae9d8f'
    - '#bf2d50'
    - '#49becf'
  brandStrength: 0.9375
  lightness: 0.14356341562233865
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
