typography_spectrum: 0.41713
color:
  brandColors:
    - '#000000'
    - '#f5f5f5'
    - '#bbab99'
    - '#687e92'
    - '#64c3b8'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6635
analytics:
  google: null
  facebook: null
  twitter: null
name: Angelos
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Apricot Forest Hellas
description: Chinese Medicine for the Few
purpose: []
