name: Angelos
favicon: null
layout_spectrum: 0.6635
typography_spectrum: 0.41713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b8a79d'
    - '#d8c9b8'
    - '#645c57'
    - '#2a2529'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
